
- name: copy oskari-server as oskari-transport
  command: cp -r {{ oskari_dir }}/oskari-server {{ oskari_dir }}/oskari-transport
  args:
    creates: "{{ oskari_dir }}/oskari-transport"

- name: Set file permissions
  file:
    path: "{{ oskari_dir }}/oskari-transport"
    owner: jetty
    group: oskari
    mode: 0775
    recurse: yes

- name: Remove extra files from transport
  file:
    path: "{{ oskari_dir }}/oskari-transport/{{ item }}"
    state: absent
  with_items:
    - geoserver_licenses
    - geoserver_data
    - setup.war
    - resources/articlesByTag
    - oskari-frontend
    - webapps/geoserver
    - webapps/oskari-front.xml
    - webapps/oskari-map.xml
    - webapps/oskari-map.war
    - webapps/READNE.TXT

# RHEL/Centos 6
- include_tasks: setup-service-initd.yml
  when: not is_systemd
  vars:
    oskari_component: oskari-transport
    server_port: "{{ oskari_transport_port }}"

# RHEL/Centos 7+
- include_tasks: setup-service-systemd.yml
  when: is_systemd
  vars:
    oskari_component: oskari-transport
    server_port: "{{ oskari_transport_port }}"
