

- name: Remove extra files from oskari-server
  file:
    path: "{{ oskari_dir }}/oskari-server/{{ item }}"
    state: absent
  with_items:
    - webapps/READNE.TXT
# Delete frontend context if nginx in use
#    - oskari-frontend
#    - webapps/oskari-front.xml

# Should we remove oskari-map as well as it should be created for the app? Or start the app with it
# Do something with setup.war?

- name: Remove GeoServer files from oskari-server
  when: not install_geoserver or not use_single_jetty
  file:
    path: "{{ oskari_dir }}/oskari-server/{{ item }}"
    state: absent
  with_items:
    - geoserver_licenses
    - geoserver_data
    - webapps/geoserver

# RHEL/Centos 6
- include_tasks: setup-service-initd.yml
  when: not is_systemd
  vars:
    oskari_component: oskari-server
    server_port: "{{ oskari_server_port }}"

# RHEL/Centos 7+
- include_tasks: setup-service-systemd.yml
  when: is_systemd
  vars:
    oskari_component: oskari-server
    server_port: "{{ oskari_server_port }}"

# chown jetty:oskari /var/run/jetty
- name: Setup pid directory for Jetty
  file:
    path: "/var/run/jetty"
    state: directory
    owner: jetty
    group: oskari
    mode: 0775
    recurse: yes

# iptables used in some environments
#    sudo iptables -A INPUT -p tcp -s localhost --dport 7701 -j ACCEPT
# https://engineering.nordeus.com/managing-iptables-with-ansible-the-easy-way/
#- iptables_raw:
#    name: allow_oskari_server
#    rules: '-A INPUT -p tcp -s localhost --dport {{ oskari_server_port }} -j ACCEPT'