---
- name: Creates directory for Oskari
  file:
    path: "{{ oskari_dir }}"
    state: directory
    owner: jetty
    group: oskari
    mode: 0775
    recurse: yes

- name: Download Oskari package on server
  when: not use_local_download
  get_url:
    url=http://oskari.org/build/server/oskari-latest-stable.zip
    dest="{{ oskari_dir }}/oskari-latest-stable.zip"

- name: Download Oskari package locally
  when: use_local_download
  get_url:
    url=http://oskari.org/build/server/oskari-latest-stable.zip
    dest="/tmp/oskari-latest-stable.zip"
  delegate_to: 127.0.0.1

- name: Copy zip from the control machine to remote host
  when: use_local_download
  synchronize:
    src: /tmp/oskari-latest-stable.zip
    dest: "{{ oskari_dir }}/oskari-latest-stable.zip"

- name: Extract archive
  unarchive:
    src: "{{ oskari_dir }}/oskari-latest-stable.zip"
    dest: "{{ oskari_dir }}"
    remote_src: yes
    owner: jetty
    group: oskari
    mode: 0775
    creates: "{{ jetty_home }}"

# Maybe delete zip as cleanup and do get_url only if Jetty-dist folder doesn't exist