---
# Tries to include vars named after the inventory file (hosts_[app]_[env], but skips if one is not found)
- name: Include vars file if one exists meeting our condition.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - custom_vars/{{ inventory_hostname }}.yml
      skip: true

# Downloads zip from oskari.org and extracts it
- include_tasks: download-oskari.yml

# Use extracted files to create separate components
# Order: GeoServer, Transport, Oskari-server as we remove files after copy

# Separate GeoServer Jetty if configured
- include_tasks: create-geoserver.yml
  when: install_geoserver and not use_single_jetty

- include_tasks: setup-logging.yml
  when: install_geoserver and not use_single_jetty
  vars:
    oskari_component: oskari-geoserver

# Main server
- include_tasks: create-server.yml
- include_tasks: setup-logging.yml
  vars:
    oskari_component: oskari-server

- include_tasks: setup-notifier.yml
  when: use_error_notifier
