
- name: Configure Notifier script
  template:
    src: error-notify.sh.j2
    dest: "{{ oskari_dir }}/error-notify.sh"
    owner: jetty
    group: oskari
    mode: 0775

- name: Setup notifier service
  template:
    src: error-notifier.service.j2
    dest: "/etc/systemd/system/oskari-error-notify.service"
    owner: jetty
    group: oskari